version: "3.4"
services:
  authservice:
    command:
      - authservice
      - run
      - --defaults=dev
    environment:
      STORJ_ALLOWED_SATELLITES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_AUTH_TOKEN: super-secret
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_ENDPOINT: http://localhost:9999
      STORJ_KV_BACKEND: memory://
      STORJ_LISTEN_ADDR: 0.0.0.0:8888
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ROLE: authservice
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/elek/storj-edge:1.19.0
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8888
        published: 8888
        protocol: tcp
  cockroach:
    command:
      - start-single-node
      - --insecure
      - --http-addr
      - 127.0.0.1:1234
    image: cockroachdb/cockroach
    networks:
      default: null
    ports:
      - mode: ingress
        target: 26257
        published: 26257
        protocol: tcp
  redis:
    image: redis:6.0.9
    networks:
      default: null
  satellite-admin:
    command:
      - satellite
      - run
      - admin
      - --defaults=dev
      - --identity-dir=/var/lib/storj/identities/1
    environment:
      STORJ_ADMIN_ADDRESS: 0.0.0.0:8080
      STORJ_CONSOLE_AUTH_TOKEN: my-suppa-secret-key
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/identities/1
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=1
      STORJ_LOG_LEVEL: debug
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_ROLE: satellite-admin
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/elek/storj:1.45.3
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: 9080
        protocol: tcp
  satellite-api:
    command:
      - satellite
      - run
      - api
      - --defaults=dev
      - --identity-dir=/var/lib/storj/identities/1
    environment:
      STORJ_ADDRESS: 0.0.0.0:7777
      STORJ_CONSOLE_ADDRESS: 0.0.0.0:10000
      STORJ_CONSOLE_AUTH_TOKEN_SECRET: my-suppa-secret-key
      STORJ_CONSOLE_GATEWAY_CREDENTIALS_REQUEST_URL: http://localhost:8888
      STORJ_CONSOLE_LINKSHARING_URL: http://localhost:9090
      STORJ_CONSOLE_OPEN_REGISTRATION_ENABLED: "true"
      STORJ_CONSOLE_RATE_LIMIT_BURST: "100"
      STORJ_CONSOLE_STATIC_DIR: /var/lib/storj/storj/web/satellite/
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/identities/1
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=0
      STORJ_LOG_LEVEL: debug
      STORJ_MAIL_FROM: Storj <yaroslav-satellite-test@storj.io>
      STORJ_MAIL_SMTP_SERVER_ADDRESS: smtp.gmail.com:587
      STORJ_MAIL_TEMPLATE_PATH: /var/lib/storj/storj/web/satellite/static/emails/
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METAINFO_RATE_LIMITER_ENABLED: "false"
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_ROLE: satellite-api
      STORJ_SERVER_ADDRESS: satellite-api:7777
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_REVOCATION_DBURL: redis://redis:6379?db=1
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_WAIT_FOR_DB: "true"
    image: ghcr.io/elek/storj:1.45.3
    networks:
      default: null
    ports:
      - mode: ingress
        target: 7777
        published: 7777
        protocol: tcp
      - mode: ingress
        target: 10000
        published: 10000
        protocol: tcp
  satellite-core:
    command:
      - satellite
      - run
      - --defaults=dev
      - --identity-dir=/var/lib/storj/identities/1
    environment:
      STORJ_DATABASE: cockroach://root@cockroach:26257/master?sslmode=disable
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/identities/1
      STORJ_LIVE_ACCOUNTING_STORAGE_BACKEND: redis://redis:6379?db=1
      STORJ_LOG_LEVEL: debug
      STORJ_METAINFO_DATABASE_URL: cockroach://root@cockroach:26257/metainfo?sslmode=disable
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_ORDERS_ENCRYPTION_KEYS: 0100000000000000=0100000000000000000000000000000000000000000000000000000000000000
      STORJ_ROLE: satellite-core
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/elek/storj:1.45.3
    networks:
      default: null
  storagenode:
    command:
      - storagenode
      - run
      - --defaults=dev
    deploy:
      replicas: 10
    environment:
      STORJ_CONSOLE_STATIC_DIR: /var/lib/storj/web/storagenode
      STORJ_DEBUG_ADDR: 0.0.0.0:11111
      STORJ_DEFAULTS: dev
      STORJ_IDENTITY_DIR: /var/lib/storj/.local/share/storj/identity/storagenode/
      STORJ_LOG_LEVEL: debug
      STORJ_METRICS_APP_SUFFIX: sim
      STORJ_OPERATOR_EMAIL: storage9@mail.test
      STORJ_OPERATOR_WALLET: "0x0123456789012345678901234567890123456789"
      STORJ_ROLE: storagenode
      STORJ_SERVER_EXTENSIONS_REVOCATION: "false"
      STORJ_SERVER_USE_PEER_CA_WHITELIST: "false"
      STORJ_STORAGE2_MONITOR_MINIMUM_DISK_SPACE: "0"
      STORJ_STORAGE2_TRUST_SOURCES: 12whfK1EDvHJtajBiAUeajQLYcWqxcQmdYQU5zX5cCf6bAxfgu4@satellite-api:7777
      STORJ_STORAGE_ALLOCATED_DISK_SPACE: 1G
      STORJ_VERSION_SERVER_ADDRESS: http://versioncontrol:8080/
      STORJ_WAIT_FOR_SATELLITE: "true"
    image: ghcr.io/elek/storj:1.45.3
    networks:
      default: null
  storjscan:
    #this image is just for the environment
    image: ghcr.io/elek/storj:1.45.3
    command:
      - /opt/storj/cmd/storjscan/storjscan
      - run
      - --database=postgres://storjscan@db/storjscandb
      - --tokens.endpoint=http://geth:8545
      - --tokens.contract=0x1E119A589270646585b044db12098B1e456a88Af
      - --api.address=0.0.0.0:12000
      - --api.keys=eu1:eu1secret
    ports:
      - 12000:12000
    volumes:
      - .:/opt/storj
    networks:
      default: null
  db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: storjscan
      POSTGRES_DB: storjscandb
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5442:5432
  geth:
    image: ethereum/client-go
    command:
      - --keystore=/test-blockchain
      - --password=/test-blockchain/pass
      - --http
      - --ws
      - --dev
      - --miner.etherbase=0x158D2c25bA6107B622F288663F50f53601ab6710
      - --http.api=eth,net,web3,txpool,admin,debug
      - --ws.api=eth,net,web3,txpool,admin,debug
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --ws.addr=0.0.0.0
      - --http.corsdomain
      - "*"
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - ./test-blockchain:/test-blockchain