version: "3.4"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: storj
      POSTGRES_DB: storjtest
  cockroach:
    command:
    - start-single-node
    - --insecure
    - --http-addr
    - 127.0.0.1:1234
    image: cockroachdb/cockroach
  redis:
    image: redis:6.0.9
    networks:
      default: null
  test:
    build: .
    command:
    - /usr/bin/sleep
    - infinity
    environment:
      STORJ_TEST_POSTGRES: "postgres://storj:secret@postgres/storjtest?sslmode=disable"

